# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - streamingfrontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_9bcf0ad3666544d188320ff0ab2613a1 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_61f8af1a2bc043afb5fa1917f3c25c19 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9bcf0ad3666544d188320ff0ab2613a1 }}/streaming-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'streamingfrontend'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_10230ca6d59942ec99e22ddf3fb16bf9 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_9bcf0ad3666544d188320ff0ab2613a1 }}/streaming-frontend:${{ github.sha }}'